[tool.black]
line-length = 88
target-version = ['py312']
skip-string-normalization = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_first_party = "module_30_ci_linters"

[tool.flake8]
max-line-length = 88
ignore = [
    "E203",  # whitespace before ‘:’
    "E501",  # line too long
    "W503",  # line break before binary operator
]
exclude = [
    ".git",
    "__pycache__",
    "*.pyc",
    "*.pyo",
    "*~",
    ".pytest_cache",
    "tests/__pycache__",
]