name: Python CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r module_30_ci_linters/requirements.txt
        pip install flake8 isort black mypy pytest

    - name: Run isort
      run: isort --check-only module_30_ci_linters/

    - name: Run black
      run: black --check module_30_ci_linters/

    - name: Run flake8
      run: flake8 module_30_ci_linters/

    - name: Run mypy
      run: mypy module_30_ci_linters/

    - name: Run tests
      run: pytest -v module_30_ci_linters/